# tasks/main.yml
---
- name: Create a namespace
  kubernetes.core:
    api_version: v1
    kind: Namespace
    name: "{{ namespace_name }}"
    state: present


- name: Create RoleBinding for edit permissions
  kubernetes.core:
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    namespace: "{{ namespace_name }}"
    name: "{{ namespace_name }}-edit-rolebinding"
    state: present
    definition:
      subjects:
      - kind: Group
        name: "{{ group_name }}"
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: edit
        apiGroup: rbac.authorization.k8s.io
